name: Create Resources

on:
  workflow_dispatch: # Manual trigger for creation
    inputs:
      confirm_create:
        description: "Type 'create' to confirm cdktf resource creation"
        required: true

jobs:
  create:
    if: ${{ inputs.confirm_create == 'create' }} # Confirmation check
    runs-on: ubuntu-latest

  job1:
    runs-on: ubuntu-latest
    steps:
      - name:  Agent Config
        id:  agent-setup
        uses: ./.github/workflows/agent-config.yml

      - name: Use Project ID and Region
        run: |
        echo "Project ID: ${{ steps.agent-config.outputs.project_id }}"
        echo "Project Region: ${{ steps.agent-config.outputs.project_region }}"

      - name: Build and Deploy
        run: |
          npm run build
          cdktf deploy --auto-approve