name: exploring GitHub Actions CI Pipelines

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Agent Config
        id:  agent-setup
        uses: ./.github/workflows/agent-config.yml

      - name: Use Project ID and Region
        run: |
          echo "Project ID: ${{ steps.agent-config.outputs.project_id }}"
          echo "Project Region: ${{ steps.agent-config.outputs.project_region }}"

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform