name: CDKTF typescript Create GH-A Workflows

on:
  workflow_dispatch: # Manual trigger for creation
    inputs:
      confirm_create:
        description: "Type 'create' to confirm cdktf resource creation"
        required: true

jobs:
  create:
    if: ${{ inputs.confirm_create == 'create' }} # Confirmation check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Shared Agent Setup
        id:  agent-setup
        uses: ./.github/workflows/agent-config.yml

      - name: Use Project ID and Region
        run: |
          echo "Project ID: ${{ steps.agent-setup.outputs.project_id }}"
          echo "Project Region: ${{ steps.agent-setup.outputs.project_region }}"

      - name: Build and Deploy
        run: |
          npm run build
          cdktf deploy --auto-approve