name: Destroy TS CDKTF Resources

on:
  workflow_dispatch: # Manual trigger for destruction
    inputs:
      confirm_destroy:
        description: "Type 'destroy' to confirm resource destruction"
        required: true

jobs:
  destroy:
    if: ${{ inputs.confirm_destroy == 'destroy' }} # Confirmation check
    runs-on: ubuntu-latest

    steps:
      - name:  Agent Config
        id:  agent-setup
        uses: ./.github/workflows/agent-config.yml

      - name: Use Project ID and Region
        run: |
          echo "Project ID: ${{ steps.agent-config.outputs.project_id }}"
          echo "Project Region: ${{ steps.agent-config.outputs.project_region }}"

      - name: Build and Deploy
        run: |
          npm run build
          cdktf destroy --auto-approve